### ISSUE TITLE
employee user id if same for multiple users than , display error message  , (user id already in use )

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#804]

**Comment by Djprem** [comment]
![20](https://cloud.githubusercontent.com/assets/20493187/25281904/7dca6788-26cc-11e7-90d8-be15836cc002.PNG)

**Comment by aafrinS** [comment]
verified and closed

**Comment by aafrinS** [comment]
when we enter same id and password for multiple user instead of showing pop-up we are getting error message through which we can't identify the problem .
![employee](https://cloud.githubusercontent.com/assets/25024115/25573733/c3a6bb8a-2e65-11e7-909d-b585a82393f5.png)

**Comment by aafrinS** [comment]
while we enter 2 digits or 2 character as user name and password ,submit button getting hided instead of showing warning message that minimum 4 character or digits required for password and user name .
![2](https://cloud.githubusercontent.com/assets/25024115/25622570/6c80fd26-2f72-11e7-8e82-f8dc0a6f81ef.png)

**Comment by dharwadkarR** [comment]
not shows any pop-up in MAPP

**Comment by ParshuM** [comment]
verify and closed
